# -*- coding: utf-8 -*-
"""Tensorflow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYyUrIPHnZ54ddkoBdvcgQot0zK2KNpz

## How to use tf.constant and tf.variable
"""

import tensorflow as tf

#tf.constant in scalar
scalar = tf.constant(7)
scalar

scalar.ndim

#tf.constant in vector
vector=tf.constant([10,10])
vector

vector.ndim

#tf.constant in matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

matrix.ndim

#tf.constant in tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                      [10,11,12]]])
tensor

tensor.ndim

# In unchangeable_tensor=tf.constant you cannot assign new values
changable_tensor=tf.Variable([[10,7]])
unchangable_tensor=tf.constant([[10,7]])
changable_tensor,unchangable_tensor

changable_tensor[0, 1].assign(10)

unchangable_tensor[1,1].assign(10)

random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

not_shuffled=tf.constant([[10,7],
                          [12,4],
                          [9,7]])
tf.random.shuffle(not_shuffled)

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

tf.ones([3,5],dtype = tf.int32)

import numpy as np
numpy_A=np.arange(1,30,dtype=np.int32)
numpy_A

a=tf.constant(numpy_A,shape=(1,1,29))

a

a.ndim

rank_2_tensor=tf.constant([[3,5],
                           [7,9]])
rank_2_tensor.shape,rank_2_tensor.ndim

rank_2_tensor[ : ,-1]

rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

tf.expand_dims(rank_3_tensor,-1) # -1 for last index,0 for initial index and 1 for 2nd index

tensor=tf.constant([[10,7],[7,9]])
tensor - 10

tensor

tf.multiply(tensor,10)

tf.multiply([[1,2],[3,4]],10)

x=tf.constant([[10,7],
               [3,4],
               [6,8]])
y=tf.constant([[1,2],
               [3,4],
               [8,9]])
tf.matmul(x,y)

tf.reshape(y,shape=(2,3))

tf.matmul(x,tf.reshape(y,shape=(2,3)))

tf.matmul(x,tf.reshape(x,shape=(2,3)))

tf.matmul(y,tf.reshape(x,shape=(2,3)))

tf.tensordot(tf.transpose(x),y,axes=0)

